package com.waltsoft.tx_purchase.business.exchange_rate.api.frankfurter;

import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

@Component
class FrankfurterCurrencyCodeConverter {

    private static final Map<String, String> CURRENCY_CODE_MAP;

    static {
        CURRENCY_CODE_MAP = new HashMap<>();
        CURRENCY_CODE_MAP.put("Euro Zone-Euro", "EUR");
        CURRENCY_CODE_MAP.put("United States-Dollar", "USD");
        CURRENCY_CODE_MAP.put("Japan-Yen", "JPY");
        CURRENCY_CODE_MAP.put("United Kingdom-Pound", "GBP");
        CURRENCY_CODE_MAP.put("Australia-Dollar", "AUD");
        CURRENCY_CODE_MAP.put("Canada-Dollar", "CAD");
        CURRENCY_CODE_MAP.put("Switzerland-Franc", "CHF");
        CURRENCY_CODE_MAP.put("China-Yuan Renminbi", "CNY");
        CURRENCY_CODE_MAP.put("Hong Kong-Dollar", "HKD");
        CURRENCY_CODE_MAP.put("New Zealand-Dollar", "NZD");
        CURRENCY_CODE_MAP.put("Sweden-Krona", "SEK");
        CURRENCY_CODE_MAP.put("South Korea-Won", "KRW");
        CURRENCY_CODE_MAP.put("Singapore-Dollar", "SGD");
        CURRENCY_CODE_MAP.put("Norway-Krone", "NOK");
        CURRENCY_CODE_MAP.put("Mexico-Peso", "MXN");
        CURRENCY_CODE_MAP.put("India-Rupee", "INR");
        CURRENCY_CODE_MAP.put("Russia-Ruble", "RUB");
        CURRENCY_CODE_MAP.put("South Africa-Rand", "ZAR");
        CURRENCY_CODE_MAP.put("Brazil-Real", "BRL");
        CURRENCY_CODE_MAP.put("Turkey-Lira", "TRY");
        CURRENCY_CODE_MAP.put("Taiwan-New Taiwan Dollar", "TWD");
        CURRENCY_CODE_MAP.put("Denmark-Krone", "DKK");
        CURRENCY_CODE_MAP.put("Poland-Zloty", "PLN");
        CURRENCY_CODE_MAP.put("Thailand-Baht", "THB");
        CURRENCY_CODE_MAP.put("Indonesia-Rupiah", "IDR");
        CURRENCY_CODE_MAP.put("Czech Republic-Koruna", "CZK");
        CURRENCY_CODE_MAP.put("Hungary-Forint", "HUF");
        CURRENCY_CODE_MAP.put("Iceland-Krona", "ISK");
        CURRENCY_CODE_MAP.put("Israel-New Shekel", "ILS");
        CURRENCY_CODE_MAP.put("Philippines-Peso", "PHP");
        CURRENCY_CODE_MAP.put("Romania-Leu", "RON");
        CURRENCY_CODE_MAP.put("Malaysia-Ringgit", "MYR");
        CURRENCY_CODE_MAP.put("Bulgaria-Lev", "BGN");
        CURRENCY_CODE_MAP.put("Chile-Peso", "CLP");
        CURRENCY_CODE_MAP.put("Colombia-Peso", "COP");
        CURRENCY_CODE_MAP.put("Peru-Nuevo Sol", "PEN");
        CURRENCY_CODE_MAP.put("Saudi Arabia-Riyal", "SAR");
        CURRENCY_CODE_MAP.put("United Arab Emirates-Dirham", "AED");
        CURRENCY_CODE_MAP.put("Argentina-Peso", "ARS");
        CURRENCY_CODE_MAP.put("Afghanistan-Afghani", "AFN");
        CURRENCY_CODE_MAP.put("Albania-Lek", "ALL");
        CURRENCY_CODE_MAP.put("Algeria-Dinar", "DZD");
        CURRENCY_CODE_MAP.put("Angola-Kwanza", "AOA");
        CURRENCY_CODE_MAP.put("Armenia-Dram", "AMD");
        CURRENCY_CODE_MAP.put("Antigua & Barbuda-East Caribbean Dollar", "XCD");
        CURRENCY_CODE_MAP.put("Bahrain-Dinar", "BHD");
        CURRENCY_CODE_MAP.put("Bangladesh-Taka", "BDT");
        CURRENCY_CODE_MAP.put("Barbados-Dollar", "BBD");
        CURRENCY_CODE_MAP.put("Belarus-Ruble", "BYN");
        CURRENCY_CODE_MAP.put("Bolivia-Boliviano", "BOB");
        CURRENCY_CODE_MAP.put("Bosnia & Herzegovina-Convertible Mark", "BAM");
        CURRENCY_CODE_MAP.put("Botswana-Pula", "BWP");
        CURRENCY_CODE_MAP.put("Costa Rica-Colon", "CRC");
        CURRENCY_CODE_MAP.put("Dominican Republic-Peso", "DOP");
        CURRENCY_CODE_MAP.put("Egypt-Pound", "EGP");
        CURRENCY_CODE_MAP.put("Georgia-Lari", "GEL");
        CURRENCY_CODE_MAP.put("Ghana-Cedi", "GHS");
        CURRENCY_CODE_MAP.put("Guatemala-Quetzal", "GTQ");
        CURRENCY_CODE_MAP.put("Honduras-Lempira", "HNL");
        CURRENCY_CODE_MAP.put("Iraq-Dinar", "IQD");
        CURRENCY_CODE_MAP.put("Jamaica-Dollar", "JMD");
        CURRENCY_CODE_MAP.put("Jordan-Dinar", "JOD");
        CURRENCY_CODE_MAP.put("Kazakhstan-Tenge", "KZT");
        CURRENCY_CODE_MAP.put("Kenya-Shilling", "KES");
        CURRENCY_CODE_MAP.put("Kuwait-Dinar", "KWD");
        CURRENCY_CODE_MAP.put("Lebanon-Pound", "LBP");
        CURRENCY_CODE_MAP.put("Morocco-Dirham", "MAD");
        CURRENCY_CODE_MAP.put("Nigeria-Naira", "NGN");
        CURRENCY_CODE_MAP.put("Oman-Rial", "OMR");
        CURRENCY_CODE_MAP.put("Pakistan-Rupee", "PKR");
        CURRENCY_CODE_MAP.put("Panama-Balboa", "PAB");
        CURRENCY_CODE_MAP.put("Paraguay-Guarani", "PYG");
        CURRENCY_CODE_MAP.put("Qatar-Riyal", "QAR");
        CURRENCY_CODE_MAP.put("Sri Lanka-Rupee", "LKR");
        CURRENCY_CODE_MAP.put("Tunisia-Dinar", "TND");
        CURRENCY_CODE_MAP.put("Ukraine-Hryvnia", "UAH");
        CURRENCY_CODE_MAP.put("Uruguay-Peso", "UYU");
        CURRENCY_CODE_MAP.put("Uzbekistan-Soum", "UZS");
        CURRENCY_CODE_MAP.put("Venezuela-Bolivar Soberano", "VES");
        CURRENCY_CODE_MAP.put("Vietnam-Dong", "VND");
        CURRENCY_CODE_MAP.put("Aruba-Florin", "AWG");
        CURRENCY_CODE_MAP.put("Azerbaijan-Manat", "AZN");
        CURRENCY_CODE_MAP.put("Bahamas-Dollar", "BSD");
        CURRENCY_CODE_MAP.put("Belize-Dollar", "BZD");
        CURRENCY_CODE_MAP.put("Bermuda-Dollar", "BMD");
        CURRENCY_CODE_MAP.put("Brunei-Dollar", "BND");
        CURRENCY_CODE_MAP.put("Burundi-Franc", "BIF");
        CURRENCY_CODE_MAP.put("Cambodia-Riel", "KHR");
        CURRENCY_CODE_MAP.put("Cape Verde-Escudo", "CVE");
        CURRENCY_CODE_MAP.put("Cayman Islands-Dollar", "KYD");
        CURRENCY_CODE_MAP.put("Central African Republic-CFA Franc", "XAF");
        CURRENCY_CODE_MAP.put("Cuba-Peso", "CUP");
        CURRENCY_CODE_MAP.put("Eritrea-Nakfa", "ERN");
        CURRENCY_CODE_MAP.put("Ethiopia-Birr", "ETB");
        CURRENCY_CODE_MAP.put("Fiji Islands-Dollar", "FJD");
        CURRENCY_CODE_MAP.put("Gambia-Dalasi", "GMD");
        CURRENCY_CODE_MAP.put("Guinea-Franc", "GNF");
        CURRENCY_CODE_MAP.put("Guyana-Dollar", "GYD");
        CURRENCY_CODE_MAP.put("Haiti-Gourde", "HTG");
        CURRENCY_CODE_MAP.put("Iran-Rial", "IRR");
        CURRENCY_CODE_MAP.put("Kyrgyzstan-Som", "KGS");
        CURRENCY_CODE_MAP.put("Laos-Kip", "LAK");
        CURRENCY_CODE_MAP.put("Liberia-Dollar", "LRD");
        CURRENCY_CODE_MAP.put("Libya-Dinar", "LYD");
        CURRENCY_CODE_MAP.put("Macao-Pataca", "MOP");
        CURRENCY_CODE_MAP.put("Macedonia-Denar", "MKD");
        CURRENCY_CODE_MAP.put("Madagascar-Ariary", "MGA");
        CURRENCY_CODE_MAP.put("Malawi-Kwacha", "MWK");
        CURRENCY_CODE_MAP.put("Maldives-Rufiyaa", "MVR");
        CURRENCY_CODE_MAP.put("Mauritania-Ouguiya", "MRU");
        CURRENCY_CODE_MAP.put("Mauritius-Rupee", "MUR");
        CURRENCY_CODE_MAP.put("Moldova-Leu", "MDL");
        CURRENCY_CODE_MAP.put("Mongolia-Tugrik", "MNT");
        CURRENCY_CODE_MAP.put("Mozambique-Metical", "MZN");
        CURRENCY_CODE_MAP.put("Myanmar-Kyat", "MMK");
        CURRENCY_CODE_MAP.put("Namibia-Dollar", "NAD");
        CURRENCY_CODE_MAP.put("Nepal-Rupee", "NPR");
        CURRENCY_CODE_MAP.put("Nicaragua-Cordoba Oro", "NIO");
        CURRENCY_CODE_MAP.put("Papua New Guinea-Kina", "PGK");
        CURRENCY_CODE_MAP.put("Rwanda-Franc", "RWF");
        CURRENCY_CODE_MAP.put("Samoa-Tala", "WST");
        CURRENCY_CODE_MAP.put("Seychelles-Rupee", "SCR");
        CURRENCY_CODE_MAP.put("Sierra Leone-Leone", "SLE");
        CURRENCY_CODE_MAP.put("Solomon Islands-Dollar", "SBD");
        CURRENCY_CODE_MAP.put("Somalia-Shilling", "SOS");
        CURRENCY_CODE_MAP.put("Suriname-Dollar", "SRD");
        CURRENCY_CODE_MAP.put("Tajikistan-Somoni", "TJS");
        CURRENCY_CODE_MAP.put("Tanzania-Shilling", "TZS");
        CURRENCY_CODE_MAP.put("Tonga-Pa'anga", "TOP");
        CURRENCY_CODE_MAP.put("Trinidad & Tobago-Dollar", "TTD");
        CURRENCY_CODE_MAP.put("Uganda-Shilling", "UGX");
        CURRENCY_CODE_MAP.put("Vanuatu-Vatu", "VUV");
        CURRENCY_CODE_MAP.put("Yemen-Rial", "YER");
        CURRENCY_CODE_MAP.put("Zambia-Kwacha", "ZMW");
    }

    public Optional<String> convert(String currency) {
        String currencyCode = CURRENCY_CODE_MAP.get(currency);
        return Optional.ofNullable(currencyCode);
    }
}
